import unittest
from tests.chal_31_coins_sum_test import CoinsSumTestCase
from tests.chal_42_coded_triangle_numbers_test import CodedTriangleNumbersTestCase
from tests.chal_48_self_powers_test import SelfPowersTestCase
from tests.chal_76_counting_summations_test import CountingSummationsTestCase
from tests.chal_81_path_sum_two_ways_test import PathSumTwoWaysTestCase
from tests.chal_82_path_sum_three_ways_test import PathSumThreeWaysTestCase
from tests.chal_102_triangle_containment_test import TrianglesContainmentTestCase

if __name__ == '__main__':
    unittest.main()
